// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sabrina.SankakuModel
{
    public partial class ImageVote
    {
        public int Id { get; set; }
        public long ImageId { get; set; }
        public int VoteValue { get; set; }
        public long UserId { get; set; }
    }
}