// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sabrina.SankakuModel
{
    public partial class Image
    {
        public Image()
        {
            ImageTag = new HashSet<ImageTag>();
        }

        public long Id { get; set; }
        public int Score { get; set; }
        public int Rating { get; set; }
        public int RatingCount { get; set; }
        public short IsAvailable { get; set; }

        public virtual ICollection<ImageTag> ImageTag { get; set; }
    }
}