// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sabrina.SankakuModel
{
    public partial class ImageTag
    {
        public int Id { get; set; }
        public long ImageId { get; set; }
        public int TagId { get; set; }

        public virtual Image Image { get; set; }
        public virtual Tag Tag { get; set; }
    }
}