// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sabrina.SankakuModel
{
    public partial class Tag
    {
        public Tag()
        {
            ImageTag = new HashSet<ImageTag>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ImageTag> ImageTag { get; set; }
    }
}