// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class Creator
    {
        public Creator()
        {
            CreatorPlatformLink = new HashSet<CreatorPlatformLink>();
            Finisher = new HashSet<Finisher>();
            IndexedVideo = new HashSet<IndexedVideo>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("DiscordUserID")]
        public long? DiscordUserId { get; set; }
        [Required]
        public string Name { get; set; }

        [InverseProperty("Creator")]
        public virtual ICollection<CreatorPlatformLink> CreatorPlatformLink { get; set; }
        [InverseProperty("Creator")]
        public virtual ICollection<Finisher> Finisher { get; set; }
        [InverseProperty("Creator")]
        public virtual ICollection<IndexedVideo> IndexedVideo { get; set; }
    }
}