// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class CreatorPlatformLink
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("CreatorID")]
        public int CreatorId { get; set; }
        [Column("PlatformID")]
        public int PlatformId { get; set; }
        [Required]
        public string Identification { get; set; }

        [ForeignKey(nameof(CreatorId))]
        [InverseProperty("CreatorPlatformLink")]
        public virtual Creator Creator { get; set; }
        [ForeignKey(nameof(PlatformId))]
        [InverseProperty(nameof(Joiplatform.CreatorPlatformLink))]
        public virtual Joiplatform Platform { get; set; }
    }
}