// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Dungeon_Text")]
    public partial class DungeonText
    {
        public DungeonText()
        {
            DungeonVariable = new HashSet<DungeonVariable>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column(TypeName = "ntext")]
        public string Text { get; set; }
        public int RoomType { get; set; }
        public int TextType { get; set; }

        [InverseProperty("Text")]
        public virtual ICollection<DungeonVariable> DungeonVariable { get; set; }
    }
}