// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Dungeon_Session")]
    public partial class DungeonSession
    {
        [Key]
        [Column("SessionID")]
        public int SessionId { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [Required]
        public string DungeonData { get; set; }
        [Required]
        public string RoomGuid { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.DungeonSession))]
        public virtual Users User { get; set; }
    }
}