// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Dungeon_Variable")]
    public partial class DungeonVariable
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("TextID")]
        public int TextId { get; set; }
        public int Position { get; set; }
        public int Type { get; set; }

        [ForeignKey(nameof(TextId))]
        [InverseProperty(nameof(DungeonText.DungeonVariable))]
        public virtual DungeonText Text { get; set; }
    }
}