// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class Event
    {
        public Event()
        {
            EventRun = new HashSet<EventRun>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string ClassName { get; set; }
        public long TriggerTime { get; set; }
        public short TriggerIfMissed { get; set; }

        [InverseProperty("Event")]
        public virtual ICollection<EventRun> EventRun { get; set; }
    }
}