// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("JOIPlatform")]
    public partial class Joiplatform
    {
        public Joiplatform()
        {
            CreatorPlatformLink = new HashSet<CreatorPlatformLink>();
            IndexedVideo = new HashSet<IndexedVideo>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        public string Url { get; set; }
        public string BaseUrl { get; set; }
        public string VideoIndexRoute { get; set; }
        public string VideoRoute { get; set; }

        [InverseProperty("Platform")]
        public virtual ICollection<CreatorPlatformLink> CreatorPlatformLink { get; set; }
        [InverseProperty("Platform")]
        public virtual ICollection<IndexedVideo> IndexedVideo { get; set; }
    }
}