// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class KinkHashes
    {
        [Key]
        [Column("UserID")]
        public long UserId { get; set; }
        [Required]
        [Column(TypeName = "ntext")]
        public string Hash { get; set; }
        public int? Privacy { get; set; }
        public string KinkList { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.KinkHashes))]
        public virtual Users User { get; set; }
    }
}