// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class Messages
    {
        [Key]
        [Column("MessageID")]
        public long MessageId { get; set; }
        [Column("AuthorID")]
        public long AuthorId { get; set; }
        [Required]
        public string MessageText { get; set; }
        [Column("ChannelID")]
        public long ChannelId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }

        [ForeignKey(nameof(AuthorId))]
        [InverseProperty(nameof(Users.Messages))]
        public virtual Users Author { get; set; }
    }
}