// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class PornhubVideos
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("URL")]
        public string Url { get; set; }
        [Required]
        public string Creator { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Required]
        public string ImageUrl { get; set; }
        [Required]
        public string Title { get; set; }
    }
}