// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class Puns
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        public string Text { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUsed { get; set; }
    }
}