// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class SabrinaSettings
    {
        [Key]
        [Column("GuildID")]
        public long GuildId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastWaifuJoiUpdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastIntroductionPost { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastTumblrUpdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastWheelHelpPost { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastDeepLearningPost { get; set; }
        public long? WheelChannel { get; set; }
        public long? FeetChannel { get; set; }
        public long? ContentChannel { get; set; }
    }
}