// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Sabrina_Version")]
    public partial class SabrinaVersion
    {
        [Key]
        public int VersionNumber { get; set; }
        [Required]
        public string Description { get; set; }
        public short WasAnnounced { get; set; }
    }
}