// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class SankakuPost
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ImageID")]
        public long ImageId { get; set; }
        [Column("MessageID")]
        public long MessageId { get; set; }
        [Column(TypeName = "datetime2(1)")]
        public DateTime Date { get; set; }
    }
}