// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Scenario_RaceNameLink")]
    public partial class ScenarioRaceNameLink
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("NameID")]
        public int NameId { get; set; }
        [Column("RaceID")]
        public int RaceId { get; set; }

        [ForeignKey(nameof(NameId))]
        [InverseProperty(nameof(ScenarioName.ScenarioRaceNameLink))]
        public virtual ScenarioName Name { get; set; }
        [ForeignKey(nameof(RaceId))]
        [InverseProperty(nameof(ScenarioRace.ScenarioRaceNameLink))]
        public virtual ScenarioRace Race { get; set; }
    }
}