// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Scenario_Name")]
    public partial class ScenarioName
    {
        public ScenarioName()
        {
            ScenarioRaceNameLink = new HashSet<ScenarioRaceNameLink>();
            ScenarioSavePlayerNameLink = new HashSet<ScenarioSavePlayerNameLink>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        public string Text { get; set; }
        public int Type { get; set; }

        [InverseProperty("Name")]
        public virtual ICollection<ScenarioRaceNameLink> ScenarioRaceNameLink { get; set; }
        [InverseProperty("Name")]
        public virtual ICollection<ScenarioSavePlayerNameLink> ScenarioSavePlayerNameLink { get; set; }
    }
}