// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Scenario_SavePlayerNameLink")]
    public partial class ScenarioSavePlayerNameLink
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("SavePlayerID")]
        public int SavePlayerId { get; set; }
        [Column("NameID")]
        public int NameId { get; set; }

        [ForeignKey(nameof(NameId))]
        [InverseProperty(nameof(ScenarioName.ScenarioSavePlayerNameLink))]
        public virtual ScenarioName Name { get; set; }
        [ForeignKey(nameof(SavePlayerId))]
        [InverseProperty(nameof(ScenarioSavePlayer.ScenarioSavePlayerNameLink))]
        public virtual ScenarioSavePlayer SavePlayer { get; set; }
    }
}