// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Scenario_RaceLink")]
    public partial class ScenarioRaceLink
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("RaceID")]
        public int RaceId { get; set; }
        [Column("RaceModifierID")]
        public int RaceModifierId { get; set; }

        [ForeignKey(nameof(RaceId))]
        [InverseProperty(nameof(ScenarioRace.ScenarioRaceLink))]
        public virtual ScenarioRace Race { get; set; }
        [ForeignKey(nameof(RaceModifierId))]
        [InverseProperty(nameof(ScenarioRaceModifier.ScenarioRaceLink))]
        public virtual ScenarioRaceModifier RaceModifier { get; set; }
    }
}