// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Scenario_RaceModifier")]
    public partial class ScenarioRaceModifier
    {
        public ScenarioRaceModifier()
        {
            ScenarioRaceLink = new HashSet<ScenarioRaceLink>();
            ScenarioSavePlayer = new HashSet<ScenarioSavePlayer>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [InverseProperty("RaceModifier")]
        public virtual ICollection<ScenarioRaceLink> ScenarioRaceLink { get; set; }
        [InverseProperty("RaceModifier")]
        public virtual ICollection<ScenarioSavePlayer> ScenarioSavePlayer { get; set; }
    }
}