// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class Users
    {
        public Users()
        {
            DungeonSession = new HashSet<DungeonSession>();
            Messages = new HashSet<Messages>();
            ScenarioSavePlayer = new HashSet<ScenarioSavePlayer>();
            Slavereports = new HashSet<Slavereports>();
            UserSetting = new HashSet<UserSetting>();
            WheelUserItem = new HashSet<WheelUserItem>();
        }

        [Key]
        [Column("UserID")]
        public long UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BanTime { get; set; }
        public string BanReason { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? MuteTime { get; set; }
        public string MuteReason { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LockTime { get; set; }
        public string LockReason { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DenialTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RuinTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SpecialTime { get; set; }
        public string SpecialReason { get; set; }
        public int? WalletEdges { get; set; }
        public int? TotalEdges { get; set; }

        [InverseProperty("User")]
        public virtual KinkHashes KinkHashes { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<DungeonSession> DungeonSession { get; set; }
        [InverseProperty("Author")]
        public virtual ICollection<Messages> Messages { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ScenarioSavePlayer> ScenarioSavePlayer { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Slavereports> Slavereports { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserSetting> UserSetting { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<WheelUserItem> WheelUserItem { get; set; }
    }
}