// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("WaifuJOI_ContentPost")]
    public partial class WaifuJoiContentPost
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(24)]
        public string ContentId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Time { get; set; }
    }
}