// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Wheel_Outcome")]
    public partial class WheelOutcome
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Time { get; set; }
        public int Type { get; set; }
        public byte IsUserReport { get; set; }
    }
}