// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Wheel_UserItem")]
    public partial class WheelUserItem
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ItemID")]
        public int ItemId { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.WheelUserItem))]
        public virtual Users User { get; set; }
    }
}