// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    [Table("Wheel_Setting")]
    public partial class WheelSetting
    {
        [Key]
        [Column("GuildID")]
        public long GuildId { get; set; }
        public int Mode { get; set; }
    }
}