// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sabrina.Models
{
    public partial class WheelChances
    {
        [Key]
        public int Difficulty { get; set; }
        public int Edge { get; set; }
        public int Task { get; set; }
        public int Denial { get; set; }
        public int Ruin { get; set; }
        public int Orgasm { get; set; }
    }
}