//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabrina.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sabrina.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, something must&apos;ve went wrong :/.
        /// </summary>
        internal static string BotReturnErrorText {
            get {
                return ResourceManager.GetString("BotReturnErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cum/ruin, use ``//came`` or ``//ruined``.
        /// </summary>
        internal static string CameRuinedInfo {
            get {
                return ResourceManager.GetString("CameRuinedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deny your orgasm.
        /// </summary>
        internal static string DenyOrgasm {
            get {
                return ResourceManager.GetString("DenyOrgasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salem forgot to update the Links again....
        /// </summary>
        internal static string ForgotLinkUpdate {
            get {
                return ResourceManager.GetString("ForgotLinkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enjoy a full orgasm.
        /// </summary>
        internal static string FullOrgasm {
            get {
                return ResourceManager.GetString("FullOrgasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ruin your orgasm.
        /// </summary>
        internal static string RuinOrgasm {
            get {
                return ResourceManager.GetString("RuinOrgasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then spin again.
        /// </summary>
        internal static string SpinAgain {
            get {
                return ResourceManager.GetString("SpinAgain", resourceCulture);
            }
        }
    }
}
